version: "3.9"

services:
  pg:
    image: postgres:16
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: travelapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 3s
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  flyway:
    image: flyway/flyway:10
    depends_on:
      pg:
        condition: service_healthy
    command: [
      "-url=jdbc:postgresql://pg:5432/travelapp",
      "-user=postgres",
      "-password=yourpassword",
      "-locations=filesystem:/flyway/sql",
      "migrate"
    ]
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql:ro
    profiles: ["migrate"]

volumes:
  pg_data: