-- V1__init.sql

-- ========== USERS (auto-increment BIGINT) ==========
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE countries (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           iso3 VARCHAR(3)   UNIQUE,
                           name TEXT        ,
                           security_rating FLOAT,
                           fun_rating      FLOAT
);

CREATE TABLE places (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        country_id  BIGINT REFERENCES countries(id) ON DELETE RESTRICT,
                        name        TEXT,
                        width       NUMERIC(10,2),
                        length      NUMERIC(10,2),
                        description TEXT,
                        rating      INT DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
                        date        DATE
);
CREATE INDEX idx_places_country ON places(country_id);

-- ========== PLACE_PHOTOS ==========
CREATE TABLE place_photos (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              place_id BIGINT   REFERENCES places(id) ON DELETE CASCADE,
                              url      TEXT ,
                              position INT  DEFAULT 0
);
CREATE INDEX idx_place_photos_place ON place_photos(place_id);

-- ========== USER <-> COUNTRIES (lista ID w User) ==========
CREATE TABLE user_countries (
                                user_id    BIGINT REFERENCES users(id)     ON DELETE CASCADE,
                                country_id BIGINT    REFERENCES countries(id) ON DELETE RESTRICT,
                                PRIMARY KEY (user_id, country_id)
);
CREATE INDEX idx_user_countries_country ON user_countries(country_id);

-- ========== USER <-> PLACES (lista ID w User) ==========
CREATE TABLE user_places (
                             user_id  BIGINT REFERENCES users(id)  ON DELETE CASCADE,
                             place_id BIGINT    REFERENCES places(id) ON DELETE CASCADE,
                             PRIMARY KEY (user_id, place_id)
);
CREATE INDEX idx_user_places_place ON user_places(place_id);

-- ========== USER <-> USER (friends, many-to-many) ==========
CREATE TABLE user_friends (
                              user_id        BIGINT REFERENCES users(id) ON DELETE CASCADE,
                              friend_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                              PRIMARY KEY (user_id, friend_user_id),
                              CHECK (user_id <> friend_user_id)
);

-- ========== PLACE <-> USER (travel buddies jako same ID) ==========
CREATE TABLE place_travel_buddies (
                                      place_id BIGINT    REFERENCES places(id) ON DELETE CASCADE,
                                      user_id  BIGINT REFERENCES users(id)  ON DELETE CASCADE,
                                      PRIMARY KEY (place_id, user_id)
);
CREATE INDEX idx_ptb_user ON place_travel_buddies(user_id);
