spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/travelapp
    username: postgres
    password: yourpassword

logging:
  level:
    org.flywaydb: debug